jasypt:
  encryptor:
    private-key-format: pem
    private-key-location: classpath:jasypt/privatepkcs8.pem
spring:
  main:
    lazy-initialization: true
  datasource:
    url: jdbc:postgresql://172.17.0.2:5432/mwvb
    username: ENC(azbEAVP/GDSJeJ3xKy17sTMx6n1s/TtiT0U1OSeKnHzlFpt3qF4y6niAFZhCltsar1qC94iqE9ZHlVjeG2NuxyPw4BWcEzyPlmUAlOalOkpXt2awwrDJbM7Kx00cPfAnSMvGNUDZorSI2srQrC+isnH6R5v9X+XxgyBWiLCMrA9S+dd80FlTv1gUkcpHDeZq0fMclJDA/HNW6k7pDmiRluGYj8BZZmjB3wzxoCjHYWoinXBTmvKQ6HQmgSQO28vAXbPMwRwBvlKhUhujfdztCguw0w2lTrELPRgPq8THbLjMvonjKdkwKWIDNgv2Ml5aR3jPMtyO0uyYMgFmD7iwnQ==)
    password: ENC(Ao/R3y3pBX4Mwqp47iwvSwxr/AXKIuJiviauHAgr3DUoo/CYjEQ2syYjKDZyg6yXomFygRFt6dE4cttzVv6kPAmrK+TMbJ4bymj9tcrrAKlGrmlxUjdah0tknwJFJNbaGSrJ8ojF06DlrSKBIONM1R0TeNohu3MjPViHgI5hEHxNt5iOGIHf0brZ9KH+hBUgmykBfXmC1XlWA3d6JQUmLbiYTkGN8CJtF6nrUC7M8Tpi4o6MLfvlC+SjKLUS0sLcJOxwr9kpIlXKvkeb4QIHTLlaobWU1D7TpCE5HHjFSt9BqzzsGVacaeBeWCmRNoxpRdYZm21TjrYRJeHPdRNJAA==)
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.163.com
    username: buildvocabulary@163.com
    password: ENC(Mfjjrt1owExe3KundfqCkJrj5Po0EqPBn0KTuG6zwDp2QmmQfb7DsfmIhDhSXGJChbT3OiM7nbwdxvDblEgmr/fwRCNQ0W2aAUubdhyOpSfsTik1/w/hHaWRaMxNLdjoAmAu+9HMyuW3hNcll99fosjwZ7uNiJwSYaNh/axMOx6tnCYT8XrBQOz4/8WWomIqJ0EW2sqp9QHXeGYUpa1AGjH6TCTd8zgNUSZNePyiB9rpBVvQg2Yx64tqNxmc4925wCxCoCcn32K+Z/pDaQyLC67xxUKHCjmoh3E3F4/RIRJzVh0rVwh2+fGWBAOHjxItBeoCx8Jpy6KoUsV9hbYCvQ==)
  redis:
    host: 172.17.0.3
    port: 6379
    database: 0

com:
  maerd_zinbiel:
    silver-apples:
      email:
        send: true
        register-complete-url: http://localhost:3000/register-complete/?token=
        change-password-url: http://localhost:3000/change-password-complete/?token=
      jwt:
        password: ENC(kMhxzC5K+wVcAna8GVavgFGfNtG5JfArLnh4zNkBHmxnjfnrBnJyCIxS/tf72y6jHLirtM+qY7gYHljl/AVYrLG9wuniUY5gBu/eOpPsMDQWRpUubvmAmZKu2stg0GKve5wFNpL0a5euxjW0ASocHQC/vhGHSH1A608Vz4NEAs6UwOwK4TSm/7xMwxFuupGYRiatMhZ8zA66/21kdL3XYas8kZMBkDlpIGEh6uKs622vXXyZctoJUJfPXlppUQs3B+g/NJYNvHf+8kM1xy1q+YZpSA9sM+000T8jyA3XeyAUntOE4h5a5P3lgsRQBrk3qsgThqIfBMsEov2O3Z1vWA==)

springdoc:
  api-docs:
    path: /api-docs

server:
  error:
    whitelabel:
      enabled: false
    path: /error

mybatis:
  type-aliases-package: backend.mwvb.entity
logging:
  level:
    com.github.maerd_zinbiel.backend.mwvb.mapper: debug

