spring:
  datasource:
    url: jdbc:postgresql://172.17.0.2:5432/mwvb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.163.com
    username: buildvocabulary@163.com
    password: YIXJPSUDNYVFHXPA

springdoc:
  api-docs:
    path: /api-docs

server:
  error:
    whitelabel:
      enabled: false
    path: /error

mybatis:
  type-aliases-package: backend.mwvb.entity
logging:
  level:
    com.github.maerd_zinbiel.backend.mwvb.mapper: debug

