spring:
  datasource:
    url: jdbc:postgresql://172.17.0.2:5432/mwvb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

mybatis:
  mapper-locations: classpath:mapping/*.xml

