jasypt:
  encryptor:
    private-key-format: pem
    private-key-location: classpath:jasypt/privatepkcs8.pem
spring:
  main:
    lazy-initialization: true
  datasource:
    url: jdbc:postgresql://localhost:5432/mwvb
    username: ENC(MtGGvKFXM5OSCk1SEVgM6rl7+pU4enOu6u8hfZKEYqRiJ4FK2b/uz5kQ2wTgHVpQP8r6qG8awzuXW6b7tZSkTELcUjI3sfOXSn4VBlQrVOzzOQHmvMuysS5Wz7msoS8TndyhgSpA9gNz0t0Gf2YlymQD6Gr393YqAVK0DdW8rjPPwCbg4ZoOlSoB/5wuxyf42jINBHIScD0nSJ8gsnyGwzFSl8Td8riNjuT1GgCwCmqKce98Lklu3f7kcu5s7jyiQJuj7I/U8+P1we+nxdmQV43m97dCTuHzNB5+Oq3ep2WLVreJ0FqOh9u7U77yemjeUgQT6gZEzxbhVf7bSt1aDQ==)
    password: ENC(J8uBSEAPzMPGHi8JJdi78j3pL2KXbURimFEBWPDV2cQzTCVP5/7qHHqpeAxwIw5kSLSksO8GQG0vPrLkJi6YsLqQp6w6RhYq3a4WBsPEPj9E1hh1VlXMRpLYHCrHdqFY1TCIFIY0/06JD5CnLl05LeFITClVOsZXdOSKNzwCFcCyeGCq4uCIDxdHHM9C7AtUaA8l4VeHtvws+dItoOnO+J5+fVi9ynymgghUVoTabHgAFmyynxnFhD6I5E0fkLC1MJYfnpu/LDv3DafStar16qQbaTt83z8iV99VKiSqKHxqUjPEZPGlEk80H8J6SNjlIdKIIlU8kuapH3obuGyIcg==)
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.163.com
    username: buildvocabulary@163.com
    password: ENC(YzCsM5OvpZd65i/kriVgwGEO9hSh+yUGneFslVRqgBmuCfcKObOshKn6TNZH3LQabgT/k+ovgIbmTndRsfGoKoWh6kTRXLt5M+isbzzqZVJABZcb/5JAXsIuO1ftA8msD8McNStl15+ehxmQUMbXqXA2nPRHnmyHMt7SutAro+3/pqAtZ1XYK3XsoPUOBsXBo0Oqnn3rGUwuUYdNCZcbrMbYc6WYSeBtjBjzzOFUCC89gYMM338IYDdAotbe6YNEz1WQc89wNTqIk8nxaAKr9GZ/03WyBbyUIigFtqU+DYe4SJxKDwPrAA0bI79SGSliXrZp9FgZjDenA+hvfu9jkw==)
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          auth: true
          starttls:
            enable: true
            required: true
  redis:
    host: localhost
    port: 6379
    database: 0

com:
  maerd_zinbiel:
    silver-apples:
      email:
        send: true
        register-complete-url: http://8.134.99.20/register-complete/?token=
        change-password-url: http://8.134.99.20/change-password-complete/?token=
      jwt:
        password: ENC(inpTt1V+zJCiBaaBqnVYDKdVTD2gpXAyBylns1f046echuDtWPDtmLFZBekeOc1FhqSUSPqBHjOS57UNmsG7IRwo9Q9d7XZPNNx/a9qP/Hw1B2h0pS1+8BL8EuukTRCVIMr5R5Gygle3FnZgjoH6LHIsHVQKDFWolvNXobejTk3iGhapZtm3HQztkp44HzKN0qb/Z/lisIx/20FvkpBmv5Qyh2AudR0G3jN0jeoRLmE7jAKPTq+JVwrxqS6vweDkRRfU1UVgQWJ+jxBfZSDxcmqs6Dq2zLGEuI1TDiEn7fTA5sAPEVFg+5I11kihfX77WX1X3wkmcvjbWCn7DpQXeA==)
springdoc:
  api-docs:
    path: /api-docs

server:
  error:
    whitelabel:
      enabled: false
    path: /error

mybatis:
  type-aliases-package: backend.mwvb.entity
logging:
  level:
    com.github.maerd_zinbiel.backend.mwvb.mapper: debug

